export const stateCityMapping: Record<string, string[]> = {
  Abia: ["Aba", "Umuahia", "Ohafia"],
  Adamawa: ["Yola", "Mubi", "Numan"],
  AkwaIbom: ["Uyo", "Eket", "Ikot Ekpene"],
  Anambra: ["Awka", "Onitsha", "Nnewi"],
  Bauchi: ["Bauchi", "Azare", "Misau"],
  Bayelsa: ["Yenagoa", "Ogbia", "Brass"],
  Benue: ["Makurdi", "Otukpo", "Gboko"],
  Borno: ["Maiduguri", "Biu", "Dikwa"],
  CrossRiver: ["Calabar", "Ikom", "Ogoja"],
  Delta: ["Asaba", "Warri", "Sapele"],
  Ebonyi: ["Abakaliki", "Afikpo", "Onueke"],
  Edo: ["Benin City", "Auchi", "Ekpoma"],
  Ekiti: ["Ado Ekiti", "Ikere Ekiti", "Ilawe Ekiti"],
  Enugu: ["Enugu", "Nsukka", "Awgu"],
  Gombe: ["Gombe", "Kaltungo", "Dukku"],
  Imo: ["Owerri", "Orlu", "Okigwe"],
  Jigawa: ["Dutse", "Hadejia", "Gumel"],
  Kaduna: ["Kaduna", "Zaria", "Kafanchan"],
  Kano: ["Kano", "Wudil", "Rano"],
  Katsina: ["Katsina", "Daura", "Funtua"],
  Kebbi: ["Birnin Kebbi", "Argungu", "Yauri"],
  Kogi: ["Lokoja", "Idah", "Okene"],
  Kwara: ["Ilorin", "Offa", "Patigi"],
  Lagos: ["Ikeja", "Surulere", "Epe", "Ikorodu", "Victoria Island", "Lekki", "Ajah", "Badagry", "Yaba", "Festac"],
  Nasarawa: ["Lafia", "Keffi", "Akwanga"],
  Niger: ["Minna", "Suleja", "Kontagora"],
  Ogun: ["Abeokuta", "Ijebu Ode", "Sango Ota"],
  Ondo: ["Akure", "Ondo Town", "Owo"],
  Osun: ["Osogbo", "Ile Ife", "Ilesa"],
  Oyo: ["Ibadan", "Ogbomosho", "Iseyin"],
  Plateau: ["Jos", "Barkin Ladi", "Pankshin"],
  Rivers: ["Port Harcourt", "Bonny", "Eleme"],
  Sokoto: ["Sokoto", "Tambuwal", "Wurno"],
  Taraba: ["Jalingo", "Wukari", "Gembu"],
  Yobe: ["Damaturu", "Potiskum", "Gashua"],
  Zamfara: ["Gusau", "Kaura Namoda", "Talata Mafara"],
  FCT: ["Abuja"],
};